name: 'jira_source_integration_tests'
version: '0.5.0'
config-version: 2
profile: 'integration_tests'


vars:
  jira_source:
    jira__comment_identifier: "comment"
    jira__component_identifier: "component"
    jira__epic_identifier: "epic"
    jira__field_identifier: "field"
    jira__field_option_identifier: "field_option"
    jira__issue_field_history_identifier: "issue_field_history"
    jira__issue_link_identifier: "issue_link"
    jira__issue_multiselect_history_identifier: "issue_multiselect_history"
    jira__issue_type_identifier: "issue_type"
    jira__issue_identifier: "issue"
    jira__priority_identifier: "priority"
    jira__project_board_identifier: "project_board"
    jira__project_category_identifier: "project_category"
    jira__project_identifier: "project"
    jira__resolution_identifier: "resolution"
    jira__sprint_identifier: "sprint"
    jira__status_category_identifier: "status_category"
    jira__status_identifier: "status"
    jira__user_group_identifier: "user_group"
    jira__user_identifier: "user"
    jira__version_identifier: "version"

    jira_schema: jira_source_integration_tests

seeds:
  jira_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    board:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    comment:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created: timestamp
        issue_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        updated: timestamp
    component:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        project_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    epic: 
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    field_option:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    issue:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created: timestamp
        work_ratio: float
        resolved: timestamp
        assignee: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"
    issue_multiselect_history:
      +column_types:
        time: timestamp
        issue_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        value: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"
    issue_field_history:
      +column_types:
        time: timestamp
        issue_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        value: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"
    sprint: 
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        complete_date: timestamp
        end_date: timestamp
        start_date: timestamp
    field: 
      +column_types:
        id: "{{ 'string' if target.name in ('bigquery', 'spark') else 'varchar' }}"